import { RoutePoint } from "./routePoint";
import type { Disruption } from "./disruption";
import type {
    CargoManifest, VesselSubType,
    TruckManifest, PlaneManifest,
} from "./manifest";

interface BaseVehicle {
    id: string;
    name: string;
    latitude: number;
    longitude: number;
    heading: number; // degrees
    status: "moving" | "delayed" | "stopped";
    cargo: string;
    temperature?: number; // Celsius
    lastUpdated: string; // ISO date string
    route: RoutePoint[];
    destination: [number, number];
    distanceTravelled?: number; // km
    currentSpeed: number; // km/h
    speedLimit?: number; // km/h
    remainingDistance?: number; // km
    remainingTime?: number; // minutes
    nextRoad?: string;
    cumulativeDistance?: number;
    dataSource?: "live" | "mock";
    company?: string;
    /** Canonical AI-consumed disruption signals affecting this vehicle.
     *
     *  Multiple producers write to this array — and ALL three modes
     *  (SIM, DEMO, LIVE) populate it the same way:
     *    - DEMO: lib/applyScenario.ts sets one Disruption per scenario hit
     *    - LIVE: weather hooks, port-risk consumer, geopolitical scraper
     *    - SIM:  empty (no disruption signals in pure simulation)
     *
     *  The AI agent (Brev) reads this field without caring which mode the
     *  app is in — the shape is the only thing it depends on. New
     *  disruption sources just push into the array; nothing branches on
     *  dataMode. See types/disruption.ts for the rationale.
     */
    disruptions?: Disruption[];
}

export interface Truck extends BaseVehicle {
    type: "truck";
    /** Road-freight cargo manifest (CMR consignment note shape) generated
     *  by the backend for the Petros mock fleet. */
    manifest?: TruckManifest;
}

export interface Ship extends BaseVehicle {
    type: "ship";
    originPort?: string;       // Port of departure (e.g. "YOKOHAMA")
    destinationPort?: string;  // AIS destination text (e.g. "ROTTERDAM")
    callSign?: string;
    imoNumber?: number;
    draught?: number;          // metres
    vesselLength?: number;     // metres (bow + stern)
    /** Vessel sub-type — drives cargo manifest shape (container / tanker /
     *  bulker / reefer / RoRo / breakbulk). Populated for the Petros mock
     *  fleet; live AIS ships leave it undefined (we don't reliably know the
     *  sub-type from AIS ship-type codes alone). See types/manifest.ts. */
    vesselSubType?: VesselSubType;
    /** Cargo manifest — what the ship is actually carrying. Populated by the
     *  backend manifest generator at /api/fleet/petros enrichment time.
     *  Undefined for live AIS ships (no manifest data available). */
    manifest?: CargoManifest;
    // Port risk fields populated by the backend RSS scraper
    // (backend/services/risk_engine.py → port_alerts table).
    destinationRisk?: "NONE" | "WARNING" | "CRITICAL";
    destinationIncident?: string;
}

export interface Plane extends BaseVehicle {
    type: "plane";
    flightNumber?: string;     // IATA flight code (e.g. "BA123")
    airline?: string;
    departureAirport?: string;
    arrivalAirport?: string;
    altitude?: number;         // metres
    /** Air-cargo manifest (IATA AWB shape) generated by the backend for
     *  the Petros mock fleet. */
    manifest?: PlaneManifest;
}

export type Vehicle = Truck | Ship | Plane;
export type VehicleType = Vehicle["type"];
